image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - yarn install --frozen-lockfile
    # Install peer dependencies
    - yarn add react react-dom
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script: yarn test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
